baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "ChiakiMayuzumi"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "ChiakiMayuzumi"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = ""
	logo = "images/cm.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light red"
    	accent  = "light green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "ChiakiMayuzumi"

 [[menu.main]]
	name   = "博客目录"
	url    = "/"
	weight = 0

 [[menu.main]]
	name   = "联系方式"
	url    = "sketch/"
	weight = 60



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true